/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProducts"];
        put?: never;
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProductById"];
        put: operations["updateProductById"];
        post?: never;
        delete: operations["deleteProductById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/attachement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadProductAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/attachement/{attachement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProductAttachmentById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/attachements/{attachement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteProductAttachmentById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProductQuestions"];
        put?: never;
        post: operations["postProductQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/questions/{question_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["postQuestionAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProductReviews"];
        put?: never;
        post: operations["postProductReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/reviews/{review_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respondToReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerToQuestionRequest: {
            username: string;
            answer: string;
        };
        AnswerToQuestionResponse: {
            /** Format: int64 */
            answerId: number;
            dateTime: components["schemas"]["DateTimeKnownEncoding"];
        } & components["schemas"]["AnswerToQuestionRequest"];
        AnswerToReviewRequest: {
            username: string;
            answer: string;
        };
        AnswerToReviewResponse: {
            /** Format: int64 */
            answerId: number;
            dateTime: components["schemas"]["DateTimeKnownEncoding"];
        } & components["schemas"]["AnswerToReviewRequest"];
        CreateProductRequest: {
            productName: string;
            productPrice: number;
            productCategory: string;
            productQuantity: number;
            productDescription?: string;
            productMaterial?: string;
            /** Format: decimal */
            productWeight?: number;
            /** Format: decimal */
            productWidth?: number;
            /** Format: decimal */
            productLenght?: number;
            /** Format: decimal */
            productHeight?: number;
        };
        /**
         * @description Known encoding to use on utcDateTime or offsetDateTime
         * @enum {string}
         */
        DateTimeKnownEncoding: "rfc3339" | "rfc7231" | "unixTimestamp";
        ErrorResponse: {
            /** Format: int32 */
            code: number;
            message: string;
        };
        GetContactResponse: {
            id: string;
        };
        GetDeliveryResponse: {
            handlingTime: string;
            shippingRates: components["schemas"]["ShippingRates"];
            additionalInfo: string;
            /** Format: date-time */
            shipmentDate: string;
        };
        GetLocationResponse: {
            id: string;
            city: string;
            country: string;
            postCode: string;
            province: string;
        };
        GetProductImgResponse: {
            /** Format: byte */
            image: string;
        };
        GetPublicationResponse: {
            duration: string;
            /** Format: date-time */
            endAt: string;
            /** Format: date-time */
            startAt: string;
            status: string;
            republish: boolean;
            endedBy: string;
        };
        GetSaleAfterServiceResponse: {
            warranty: components["schemas"]["WarrantyResponse"];
            returnPolicy: components["schemas"]["ReturnPolicyResponse"];
            userWarranty: components["schemas"]["UserWarrantyResponse"];
        };
        GetStockResponse: {
            /** Format: int32 */
            avaiable: number;
            unit: string;
        };
        GetTaxResponse: {
            rates: components["schemas"]["RatesResponse"];
        };
        GetValidationResponse: {
            error: string[];
            warnings: string[];
            /** Format: date-time */
            validationDate: string;
        };
        InvalidRequestError: {
            /** @enum {number} */
            code: 400;
            /** @enum {string} */
            message: "Invalid Request";
        } & WithRequired<components["schemas"]["ErrorResponse"], "code" | "message">;
        NotFoundError: {
            /** @enum {number} */
            code: 404;
            /** @enum {string} */
            message: "Not Found";
        } & WithRequired<components["schemas"]["ErrorResponse"], "code" | "message">;
        ProductDetailsResponse: {
            id: string;
            category: string;
            attachments: components["schemas"]["GetProductImgResponse"][];
            delivery: components["schemas"]["GetDeliveryResponse"];
            publication: components["schemas"]["GetPublicationResponse"];
            language: string;
            validation: components["schemas"]["GetValidationResponse"];
            saleAfterService: components["schemas"]["GetSaleAfterServiceResponse"];
            stock: components["schemas"]["GetStockResponse"];
            contact: components["schemas"]["GetContactResponse"];
            locations: components["schemas"]["GetLocationResponse"];
            tax: components["schemas"]["GetTaxResponse"];
        };
        QuestionRequest: {
            question: string;
        };
        QuestionResponse: {
            /** Format: int64 */
            questionId: number;
            username: string;
            question: string;
            dateTime: components["schemas"]["DateTimeKnownEncoding"];
        };
        RatesResponse: {
            /** Format: float */
            rate: number;
            country: string;
            province: string;
        };
        ReturnPolicyResponse: {
            id: string;
        };
        ReviewRequest: {
            /** @enum {number} */
            rate: 1 | 2 | 3 | 4 | 5;
            comment?: string;
        };
        ReviewResponse: {
            /** Format: int16 */
            reviewId: number;
            username: string;
            dateTime: components["schemas"]["DateTimeKnownEncoding"];
        } & components["schemas"]["ReviewRequest"];
        ShippingRates: {
            id: string;
        };
        UnauthorizedError: {
            /** @enum {number} */
            code: 401;
            /** @enum {string} */
            message: "Unauthorized";
        } & WithRequired<components["schemas"]["ErrorResponse"], "code" | "message">;
        UpdateProductRequest: {
            productName?: string;
            productDescription?: string;
            productPrice?: number;
            productCategory?: string;
            productQuantity?: number;
            /** Format: int32 */
            stockQuantity?: number;
        };
        UploadProductImgRequest: {
            /** Format: byte */
            image: string;
        };
        UploadProductImgResponse: {
            success: boolean;
            attachementId: string;
        };
        UserWarrantyResponse: {
            id: string;
        };
        WarrantyResponse: {
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailsResponse"][] | components["schemas"]["InvalidRequestError"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    createProductReq: components["schemas"]["CreateProductRequest"];
                };
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailsResponse"] | components["schemas"]["InvalidRequestError"] | components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    getProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailsResponse"] | components["schemas"]["InvalidRequestError"];
                };
            };
        };
    };
    updateProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    updateProductReq: components["schemas"]["UpdateProductRequest"];
                };
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailsResponse"] | components["schemas"]["InvalidRequestError"] | components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    deleteProductById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"] | components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    uploadProductAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": {
                    uploadProductImgReq: components["schemas"]["UploadProductImgRequest"];
                };
                "image/jpg": {
                    uploadProductImgReq: components["schemas"]["UploadProductImgRequest"];
                };
                "image/png": {
                    uploadProductImgReq: components["schemas"]["UploadProductImgRequest"];
                };
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadProductImgResponse"] | components["schemas"]["InvalidRequestError"] | components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    getProductAttachmentById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                attachement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": components["schemas"]["GetProductImgResponse"];
                    "image/jpg": components["schemas"]["GetProductImgResponse"];
                    "image/png": components["schemas"]["GetProductImgResponse"];
                    "application/json": components["schemas"]["NotFoundError"] | components["schemas"]["InvalidRequestError"];
                };
            };
        };
    };
    deleteProductAttachmentById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                attachement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidRequestError"] | components["schemas"]["UnauthorizedError"] | components["schemas"]["NotFoundError"];
                };
            };
            /** @description There is no content to send for this request, but the headers may be useful.  */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProductQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"][] | components["schemas"]["InvalidRequestError"] | components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    postProductQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionResponse"] | components["schemas"]["InvalidRequestError"] | components["schemas"]["UnauthorizedError"] | components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    postQuestionAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                question_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    postAnswerReq: components["schemas"]["AnswerToQuestionRequest"];
                };
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerToQuestionResponse"] | components["schemas"]["InvalidRequestError"] | components["schemas"]["UnauthorizedError"] | components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    getProductReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"][] | components["schemas"]["InvalidRequestError"] | components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    postProductReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"] | components["schemas"]["InvalidRequestError"] | components["schemas"]["NotFoundError"] | components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    respondToReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerToReviewRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerToReviewResponse"] | components["schemas"]["InvalidRequestError"] | components["schemas"]["NotFoundError"] | components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
